version: "3.3"

services:
  sql_db:
    image: postgres:latest
    container_name: "restoranding"
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=restoranding
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sql_db/restoranding
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '7500:7500'
    depends_on:
      - sql_db
    user: appuser
    volumes:
      - ./backend:/app
      - ~/.m2:/home/appuser/.m2
    working_dir: /app
    command: './mvnw spring-boot:run'
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
  db-data:
    driver: local